#ifndef DEVICE_SECRETS_DEFAULTS_H
#define DEVICE_SECRETS_DEFAULTS_H

#define DEVICE_SECRET_WIFI_SSID ""
#define DEVICE_SECRET_WIFI_PASS ""
#define DEVICE_SECRET_MQTT_HOST ""
#define DEVICE_SECRET_MQTT_PORT 1883
#define DEVICE_SECRET_MQTT_USER ""
#define DEVICE_SECRET_MQTT_PASS ""
#define DEVICE_SECRET_UDP_HOST ""
#define DEVICE_SECRET_UDP_PORT 4000
#define DEVICE_SECRET_NODE_ID "mic_node"

#endif
